ministryofjustice/hmpps-digital-prison-reporting-lib

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/CaseloadService.kt
Fix the 401 response we receive when calling the /me/caseloads endpoint.
=> DPR2-177 use token value instead of token object

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/IsoLocalDateTypeAdaptor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/JsonFileProductDefinitionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/LocalDateTypeAdaptor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepositoryAutoConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SchemaField.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/main/resources/productDefinition.json, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
This PR changes the Product Definition Repository and its date converter into default implementations of interfaces, which are autoconfigured in the absence of other beans that fulfil the interface.
This means that the client application should be able to provide its own implementation (e.g. sourced from DDB, hardcoded in the app) while leaving the existing API usage of the library's definitions unchanged.
Alternatively, the client can set the property `lib.definition.location` to use the default repository implementation with their own JSON production definition.
=> [DPR-122] Externalisable product definition

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt
This PR changes the caseload filter 
from:
```
(origin_code IN ${caseloads} or destination_code IN ${caseloads});
```
To:
```
(origin_code IN ${caseloads} AND direction='OUT') 
OR
(destination_code IN ${caseloads} AND direction='IN');
```
Tests have been modified and new added accordingly.
=> Dpr2-190 - In/Out filter

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ReportDefinitionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ConfiguredApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionServiceTest.kt, src/test/resources/productDefinition.json, src/test/resources/productDefinition2.json
This is the second PR for DPR2-72 to fulfil the following AC:
> If returnAsStaticOptions is true:
> 
> The unique values for the field are requested when the definition is requested, and included as staticOptions (as with the existing ones).
When the report definition is requested, for each report field which is a dynamic filter and has the flag returnAsStaticOptions set to true, the list of static options is populated in the response and contains all the available distinct values of that field. 
There is no prefix filtering in this case nor any other filters when performing the SQL query, apart from the caseload checks.
=> DPR2-72 return static options from definition endpoint when returnAsStaticOptions is true

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AbstractProductDefinitionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/JsonFileProductDefinitionRepository.kt
Introduced AbstractProductDefinitionRepository to provide a default implementation for getSingleReportProductDefinition to reuse the method as it seems a common use case as it is.
=> Refactor product definition repository to reuse get product definition

.trivyignore, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ParameterType.kt
The hospital and court movements definition contains a report field of type "time".
These changes to the library are to support this new type.
=> DPR2-261 update lib to handle parse time field

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ReportDefinitionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/RenderMethod.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ParameterType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/RenderMethod.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/policyengine/Effect.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/policyengine/Policy.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/policyengine/PolicyType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ConfiguredApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt, src/test/resources/productDefinitionPolicyNoAction.json
This PR implements the new policy type "access".
Main changes include:
- Support "access" type policy. Including being able to parse this from JSON.
- Support policies with missing action.
=> DPR2-299 access policy implementation

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
Changes for the single report definition endpoint to return HTML as the type of fields which have a `make_url` formula.
=> DPR2-404 return HTML type for make_url formula fields

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReportField.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Visible.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/resources/productDefinition.json
Updated the logic of parsing and outputting the "visible" and "mandatory" fields based on the below rules:
```
The DPD no longer needs a "mandatory" column.
The DPD "visible" tristate property maps like:
DPD "true": UI: "visible": true, "mandatory": false
DPD "false": UI: "visible": false, "mandatory": false
DPD "mandatory": UI: "visible": true, "mandatory": true
The UI model should have "visible" as a boolean, like before the DPD change.
```
If the visible field is not present in the DPD I defaulted it to true and the mandatory to false in the resulting UI model.
=> DPR2-413 more changes to visible field parsing based on recent details

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
There are 3 named stages currently in the query,  stage_1, stage_2 and stage_3.
These have been named to  dataset_,  policy_ and filter_ respectively.
stage_4 did not exist and pagination is part of the final select which includes the order by, limit and offset clauses
=> DPR2-427 rename existing stages 1, 2 and 3

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngineTest.kt
This is addressing issue https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/122.
With these changes the format_date formula returns an empty string for null dates which is consistent with the behaviour of other formulas.
=> DPR2-517 format_date returns empty string for null date

.circleci/config.yml, CHANGELOG.md, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTestContainersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ExternalMovementEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/resources/application-test.yml, src/test/resources/productDefinition.json
This PR addresses https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/111.
These changes fix the error when trying to filter by Boolean fields.
TestContainers were reintroduced to reproduce the failing scenario in a test as this problem was DB specific since it was occurring only on Redshift and not locally when the in memory H2 DB was used.
Therefore, using TestContainers with Postgres replicated the failure.
As TestContainers increase the build time significantly they were used only for the required test and not across all tests.
=> DPR2-518 Fixed issue with filtering error on Boolean fields.

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/StatementExecutionStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
These changes create the API which returns the status of the async query execution.
=> Dpr2 724 execute statement status api

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt
When there were no filters provided the asynchronous query execution endpoint was throwing an error.
This PR fixes this issue.
=> Dpr2 729 no filters validation error

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
These changes create a new endpoint to get the executed statement results.
Note: This does not include pagination at this point.
Documentation References: 
https://docs.aws.amazon.com/cli/latest/reference/redshift-data/get-statement-result.html
https://docs.aws.amazon.com/redshift-data/latest/APIReference/API_GetStatementResult.html
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/redshiftdata/RedshiftDataClient.html#getStatementResult(software.amazon.awssdk.services.redshiftdata.model.GetStatementResultRequest)
=> Dpr2 730 get results endpoint

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/redshiftdata/StatementExecutionStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/redshiftdata/StatementResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
These changes include:
- Addition of nextToken request and response parameters to the getStatementResult endpoint to support pagination as described in the [AWS docs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/redshiftdata/RedshiftDataClient.html#getStatementResult(software.amazon.awssdk.services.redshiftdata.model.GetStatementResultRequest)).
- Added the resultSize field to the StatementExecutionStatus response.
=> Dpr2 758 Make use of nextToken

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepositoryAutoConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/redshiftdata/StatementExecutionResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/TableIdGenerator.kt, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/TableIdGeneratorTest.kt
This PR changes the functionality of the endpoint for asynchronous query execution.
The result of the query is now stored in an external table and the endpoint returns the table ID and the statement execution ID.
The results endpoint now accepts a table ID path parameter and a pageSize and selectedPage query parameters which allow for pagination.
It also runs a synchronous query using the JDBCTemplate.
=> Dpr2 758 Pagination through use of external tables

CHANGELOG.md, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/RedshiftDataApiConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Datasource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/redshiftdata/StatementExecutionStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/resources/productDefinitionBodmis.json, src/test/resources/productDefinitionNomis.json
Main changes in this PR:
- New AthenaAPIRepository which queries Athena.
- Datasource supports two new optional fields: database and catalog.
- Added functionality to call the Athena API to start the query execution and retrieve the execution status for nomis and bodmis reports based on the datasource name.
- Existing datamart reports will run against the Redshift Data API.
Filters are not supported yet for nomis and bodmis reports as part of this release.
- The `/report/statements/{statementId}/status` endpoint has changed to
`/reports/{reportId}/{reportVariantId}/statements/{statementId}/status`
=> Dpr2 790 async athena reports

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/RedshiftDataApiConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt
These changes fix the issue due to which the Redshift async query was failing when the parameters' values were passed using the requestBuilder.parameters method from the Redshift Data Api.
Redshift Data API does not allow this inside CREATE EXTERNAL TABLE commands and throws this error:
`"ERROR: there is no parameter $1"`
The values are now replaced directly into the query string of the filter_ CTE.
Since this is isolated in the filter_ CTE it is not a concern for SQL injection.
=> Dpr2 817 Fix Redshift Error When Passing Filters

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/resources/productDefinitionNomis.json
Make datasource name comparisson case insensitive for the async APIs in order to decided weather to call Redshift or Athena.
=> DPR2-790 case insensitive datasource name comparisson

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt
Change the way we resolve Filters and Policy CTEs from WHERE TRUE and WHERE FALSE clauses to WHERE 1=1 and 0=1 respectively  in the SQL queries in order to provide support also for Oracle.
=> Dpr2 852 change where clauses

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DynamicFilterOption.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/JsonFileProductDefinitionRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/resources/nonMatchingDatasetProductDefinition.json
This is just some refactoring and does not include actual changes for DPR2-796. 
The main change is the removal of the [map function](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/main/src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt#L39) which was not used.
This was needed to be done at some point and since the changes for DPR2-796 will touch this area, I created the PR to do this incrementally.
=> DPR2-796 refactoring

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt
Previously the code to format the date was reusing the interpolateStandardFormula which works but it is unnecessary as in this case the only placeholder in the format_date formula is ${date}. 
So the code can be simplified and in this case instead of converting to string, keep the date type to use this in order to decide how to parse and format the date object.
=> DPR2-796 simplify date formula interpolation code

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AbstractProductDefinitionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Dataset.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Parameter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/resources/productDefinitionWithParameters.json
These changes:
- Support a list of parameters in the DPD Dataset.
- Convert the list of parameters to a list of report field with attached filters.
- The schema of the parameter object is assumed to be the following:
```
{
"index": 0,
"name": "prisoner_number",
"filterType": "text",
"reportFieldType": "string",
"display": "Enter NOMS Number",
"description": "@Prompt('Enter NOMS Number',,,mono,free,Not_Persistent,User:1)",
"mandatory": "true"
}
```
filterTypes currently supported on the Back End:
"Radio", "Select", "daterange", "autocomplete", "text", "date"
reportFieldTypes currently supported on the Back End:
"boolean", "date", "datetime", "double", "float", "int", "long", "string", "time", "timestamp"
=> DPR2-820 convert parameters to filters

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt, src/test/resources/productDefinitionWithParameters.json
Filters converted from parameters are validated based on whether they have matching parameter names.
With these changes the filters that were converted from parameters are extracted from the filters based on whether they have matching parameter names and put into a prompts map since (as part of later changes) they will be used to construct the prompts CTE in the repository for the async calls.
=> DPR2-980 Filters converted from parameters proper validation

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
These changes: 
- Put the filters which originated from the DPD parameters into a prompts_ CTE in the Athena query.
Example prompts_ CTE:
`"WITH $PROMPTS AS (SELECT ''filterValue1'' AS filterName1, ''filterValue2'' AS filterName2 FROM DUAL)"`
=> Dpr2 939 prompts support

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
If the main dataset query has a dataset_ CTE embedded, then the query is used as is, without recreating the dataset_ CTE in the Athena queries.
=> DPR2-996 use main report query as is if it has dataset_ cte embedded

CHANGELOG.md, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
- Added lazy loading of summary data if not yet created (works for both RedShift and Athena, but should only be used for Athena).
- Added use of coroutines to allow app to wait for table creation without blocking.
=> [DPR2-778] Lazy loading of summary data

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Report.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReportFilter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
Adds a new CTE in the Athena queries:
- Before the policy_ CTE and after the dataset_ CTE.
- It is named prefilter_ CTE.
- Takes its value from the report.filter.query field.
- Takes its name from the report.filter.name field.
- If it the report.filter field does not exist the prefilter_ CTE defaults to prefilter_ AS (SELECT * FROM dataset_).
=> DPR2-1003 make use of prefilter_ CTE for Athena queries

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngineTest.kt
These changes fix an issue with the format_date formula due to which the formula was returning an empty string when applied to date columns whose name was other than 'date'.
=> DPR2-1020 fixed format_date formula bug

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
Change the Athena query configuration to make use of the following workgroup which has been setup:
`dpr-generic-athena-workgroup`
The results of the Athena queries will be stored in:
[s3://dpr-working-development/dpr](https://eu-west-2.console.aws.amazon.com/s3/buckets/dpr-working-development/dpr/)
Providing client configuration in the library for the S3 location will have no effect since the workgroup has been setup to override client configuration.
See below:
https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/digital-prison-reporting/modules/athena_workgroups/variables.tf#L24
=> Dpr2 945 athena workgroup

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
Defaulted visible to false for the report fields generated from DPD parameters (prompts).
=> DPR2-1039 defaulted visible to false

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
Default mandatory report field to false as it appears defaulting only visible to false does not hide the field from the report.
More info: https://dsdmoj.atlassian.net/browse/DPR2-413
=> Dpr2 1039 mandatory false to hide

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
Added some logging when there are no matching schema fields for the projected columns of the query.
=> Added logging.

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/MetricDefinitionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardChartTypeDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/MetricDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Dashboard.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardChartType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Metric.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ProductDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionService.kt, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/MetricDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionServiceTest.kt, src/test/resources/productDefinitionWithMetrics.json
These changes add 3 new endpoints:
- `/definitions/dashboards`
- `/definitions/{dataProductDefinitionId}/dashboards/{dashboardId}`
- `/definitions/{dataProductDefinitionId}/metrics/{metricId}`
These return all dashboard definitions, a given dashboard definition and a given metric definition respectively.
=> Dpr2 1119 Metric Definitions

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/MetricDefinitionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/ReportDefinitionSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ProductDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/MetricDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt, src/test/resources/productDefinitionWithMetrics.json
Removed the `/definitions/dashboards` endpoint and added the dashboard definitions to the ReportDefinitionSummary which is returned as part of the existing `/definitions` endpoint.
=> DPR2-1119 Dashboard definitions part of ReportDefinitionSummary

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/ChartTypeDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/MetricDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ChartType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Dashboard.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Metric.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/MetricDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt, src/test/resources/productDefinitionWithMetrics.json
Changed include:
1. Removed visualisationType from DashboardMetricDefinition.
2. Removed visualisationType from MetricDefinition.
3. Added the optional boolean group  to the metric specification.
4. Added the optional array field chart to the metric specification.
This is in-line with https://github.com/ministryofjustice/hmpps-digital-prison-reporting-frontend/pull/219 .
=> Dpr2 1220 amend definition

CHANGELOG.md, settings.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/ReportDefinitionSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt
- first cut of plugging in auth at a per dpd level, using the policy of the dpd to determine if a user has access
=> [DPR2-1519] check dpd policy and return auth flag

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/LegacyReportSupportService.kt
These changes fix the issue with Bean ambiguity causing the application to crash at startup.
Since both AthenaApiRepository and EstablishmentCodesToWingsCacheService are annotated as Service and one is a subclass of the other Spring did not know which one to inject when AthenaApiRepository was autowired. 
Annotating AthenaApiRepository as primary fixes this.
=> DPR2-1076 Fix Bean ambiguity issue

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/establishmentsAndWings/EstablishmentsToWingsRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/estcodesandwings/EstablishmentCodesToWingsCacheService.kt
Use existing time stopwatch method as getDuration() throws a classNotFound error.
=> DPR2-1076 use existing stopwatch method

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ProductDefinitionTokenPolicyChecker.kt, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Fixed issue with ProductDefinitionTokenPolicyChecker not visible for automatic DI in hosts of the library.
=> DPR2-1076 added ProductDefinitionTokenPolicyChecker to conf imports

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SingleDashboardProductDefinition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngine.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ProductDefinitionTokenPolicyChecker.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiServiceTest.kt, src/test/resources/productDefinition.json, src/test/resources/productDefinitionWithFormula.json, src/test/resources/productDefinitionWithParameters.json
- Updated remaining endpoints with authorisation policy check
- switched authCheck to only check access level policy types, was failing row level policies
- fixed tests adding default access level policy when needed
=> [DPR2-1521] refactor authCheck to only execute access level policies

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
This is fixing the below error:
`Error: Unexpected error: Handler dispatch failed: java.lang.NoSuchMethodError: 'java.time.Duration org.apache.commons.lang3.time.StopWatch.getDuration()'`
=> NO-JIRA- Fixed issue with Stopwatch duration call

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Parameter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReferenceType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/resources/productDefinitionWithParameters.json
The main changes are:
- The report definition establishment code parameter now is expected to have a "referenceType" of "establishment" instead of a "specialType" of "establishment_code".
- RefreshCacheSchedulingService was included in the AutoConfiguration.imports.
=> DPR2-1606 Changed specialType:establishment_code to referenceType:establishment

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/DigitalPrisonReportingExceptionHandler.kt
There is a userMessage and a developerMessage being returned as part of the error responses.
The developer message is collapsed behind an accordion on the FE.
These changes remove the stack trace from the userMessage when there is a 500 response and replace it with a generic error message.
=> DPR2-1251 remove stacktrace from userMessage

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/DigitalPrisonReportingExceptionHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt
With these changes a 404 is returned instead of 500 when the results endpoints are called and the relevant Redshift table has been removed.
=> DPR2-1676 Return 404 instead of 500 when there is no results table

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt
The status endpoints check if a table is missing only if the status is 'FINISHED' and there is a table ID provided as a query parameter.
This has been causing the polling page to break when polling for the status as the table ID is generated and returned to the FE along with the execution ID when the query execution endpoint is called.
But the table does't exist yet since the query hasn't finished.
So when the FE is polling to request the status the API responds with 404.
=> DPR2-1677 The status endpoints check if a table is missing only if the status is FINISHED

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Dashboard.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTestContainersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt
These changes allow dashboards to run queries based on the datasource.
Dashboards now support also Athena queries, reportFilter (prefilter_) and non interactive filters.
Prompts are supported if passed in as non interactive filters but to make the FE aware of these changes also to the dashboard definition response will need to be made to convert the parameters to filterFields.
=> Dpr2 1745 dashboard queries based on datasource

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/policyengine/Condition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/CaseloadProvider.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DefaultCaseloadProvider.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DprAuthAwareAuthenticationToken.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/DataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DefaultCaseloadProviderTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiServiceTest.kt
This allows to filter by a list of caseloads a user has access to:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/pull/33
```json
"policy": [
{
"id": "caseloads",
"type": "row-level",
"action": ["establishment_code in (${caseloads})"],
"rule": [
{
"effect": "permit",
"condition": [
{
"exists": ["${caseloads}"]
}
]
}
]
}
],
```
=> IR-778 Add ability to get the list of caseloads a user has and use this for policy checks

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt
This fixes a bug with the caseload list generation.
Was: 
```
MDI,BXI,LEI
```
Should be:
```
'MDI','BXI','LEI'
```
Updated test to check this.
=> IR-778 🐛 Update case load handling in PolicyEngine to correct string formatting and update test cases

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiSyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/policyengine/Condition.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/CaseloadProvider.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DefaultCaseloadProvider.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DprAuthAwareAuthenticationToken.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/CommonDataApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DefinitionMapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngine.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/DashboardDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/DefaultCaseloadProviderTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiServiceTest.kt, src/test/resources/productDefinition.json, src/test/resources/productDefinitionWithDashboard.json
These changes provide support for filters of type `caseloads` and `multiselect`. 
These are passed to the API request as one query parameter per filter with a comma separated list of values:
`filters.someMultiselectFilter=a,b,c`
Filters of type 'caseloads' in the DPD are converted to filters of type multiselect in the definition response having their static options list populated with the user caseloads.
In the DPD the reportField name has to reference an existing dataset schema field for a projected column which is returned from the main dataset query.
This is the standard functionality as for all filters in order to be included correctly to the filters CTE in the overall query.
So for a multiselect its values will be checked in an OR condition.
=> Dpr2 1792 caseloads filter type

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt
These changes add a new dashboard status endpoint to support running dashboards for legacy nomis/bodmis reports.
=> DPR2-1841 new dashboard status endpoint

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt
Added new dashboard execution cancellation endpoint to support running dashboards for legacy nomis/bodmis reports.
=> DPR2-1843 new dashboard cancel statement endpoint

CHANGELOG.md, src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
Changes to fix the issue in which ${tableId} was not replaced in intermediate queries.
=> DPR2-1873 fixed issue with replacing tableId in intermediate queries
