ministryofjustice/hmpps-digital-prison-reporting-lib

README.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/OpenApiDocumentationConfiguration.kt

Updated readme, swagger class and bean names and version number.

Dpr2 69 update readme

---

README.md
build.gradle.kts

This PR fixes the error with publishing locally.

sign only for maven central publishing

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt

A small syntax issue in true PostgreSQL (not with RedShift).

[DPR-122] Fix count query for PSQL

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ConfiguredApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
src/test/resources/productDefinition.json

This PR is addressing this comment:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/21#discussion_r1378547228

DPR2-190 Address review comment to handle caseloads special case only for external-movements.

---

.circleci/config.yml
README.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ExternalMovementEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/PrisonerEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt
src/test/resources/productDefinition.json

- Added testcontainers to reproduce recurring PostgreSQL grammar issues.
- Fixed PSQL grammar issues.

[DPR-122] Testcontainers and PSQL grammar fix

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/JsonFileProductDefinitionRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepositoryAutoConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/SchemaFieldTypeDeserializer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Datasource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ParameterType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ProductDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SingleReportProductDefinition.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionServiceTest.kt
src/test/resources/productDefinition.json

More changes to comply with the json schema definition:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/32/files
Changes include:
Field types from and to json to lowercase: string, date, long as they are defined in the json schema defintion.
DataSource to datasource

Dpr2 221 additional alignment changes

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt

This change is based on @dominic-messenger-moj suggestion in this thread to make the count query more performant:
https://mojdt.slack.com/archives/C04Q49Y9E6T/p1702026101049979?thread_ts=1701965703.877759&cid=C04Q49Y9E6T

Change COUNT(*) to COUNT(1) to make query more performant

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ExternalMovementEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/JsonFileProductDefinitionRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/PrisonerEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt
src/test/resources/dpd001-court-hospital-movements.json
src/test/resources/productDefinition.json

PR to support changes in the data product definition:
https://dsdmoj.atlassian.net/browse/DPR2-280

DPR2-280 library changes to cater for updated definitions

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ReportDefinitionController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/FilterTypeDeserializer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DynamicFilterOption.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionServiceTest.kt
src/test/resources/productDefinition.json

- Fix for filter type mapping case sensitivity issues.
- Fix for missing Select filter in one of the enums.
- Fix for unexpectedly few autocomplete options being returned (moved max options from endpoint to DPD).
- Fix for BigDecimal filter option mapping.

[DPR2-282] Bug fixes and user feedback

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ConfiguredApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/PolicyEngineTest.kt
src/test/resources/productDefinitionWithFormula.json

Implementation of formula interpolation for data fields.

Dpr2 341 Formula interpolation of dataset fields

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt

Added min and max date filter.

Dpr2 322 min and max date filter

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FieldDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReportField.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt

Added "mandatory" to the report fields.

Dpr2 413 add mandatory field

---

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SchemaField.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt
src/test/resources/productDefinition.json

Fall back to dataset display if report field display is empty

DPR2-267 Fall back to dataset display if report field display is empty

---

CHANGELOG.md
build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt
src/test/resources/application-test.yml

Added CHANGELOG.md file and removed testcontainers.

DPR2-422 added CHANGELOG.md and removed testcontainers

---

CHANGELOG.md
integrating-with-library.md

Linked changelog and added initial changelog entry.

DPR2-437 linked changelog and added initial changelog entry

---

README.md

Created https://dsdmoj.atlassian.net/browse/DPR-680 based on the following Google group email
https://groups.google.com/a/digital.justice.gov.uk/g/DigitalPrisonReporting/c/YrxphYyFt2k
and added documentation for OSSRH account credential management changes.

DPR-680 Update OSSRH account credential management documentation

---

integrating-with-library.md

Addressing the following issue raised by the non-associations team.
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/107

DPR2-492 Fix broken link of AuthAwareTokenConverter

---

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ConfiguredApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/FormulaEngineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/resources/productDefinitionWithFormula.json

This PR includes changes to support the format_date formula.

DPR2-489 Support date formulas

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReportField.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/resources/productDefinition.json

Changes to make report variant display field optional.

DPR2-502 make report variant display field optional

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/DigitalPrisonReportingExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/config/RedshiftDataApiConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTestContainersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt

The following PR is creating the asynchronous execute statement API using Redshift data.
Note: This is pending cross account connectivity so the call will not work until this is resolved.

Dpr2 666 execute query api

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt

These changes fix the bug in which an error was thrown when the filters contained a dot in the key name.

Dpr2 753 Date filter validation error for Asyn execute statement endpoint.

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt

Added an endpoint to get the number of rows of the external table.

DPR2-794 added count endpoint

---

CHANGELOG.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/ConfiguredApiController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/redshiftdata/StatementCancellationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt

Added the endpoint to cancel asynchronous statements which are still running.

Dpr2 761 cancel statement

---

CHANGELOG.md

Change lib version as 4.6.1 was already published

DPR2-980 change lib version as 4.6.1 was already published

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt

Added debug logs to log the full async queries.

no-jira added debug log for async queries

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt

These changes create and prepend the context_ CTE into the Athena queries.
More information regarding the context CTE details:
https://dsdmoj.atlassian.net/wiki/spaces/DPR/pages/4977983609/Converting+Business+Objects+to+a+CTE+Dataset+Structure#context_

DPR2-996 Context_ CTE in Athena queries

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt

Changes to rename prefilter_ CTE to report_ CTE.

DPR2-1017 renamed prefilter_ CTE to report_ CTE

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt

Added comment with DPD and report details to the Athena query.

Dpr2 1022 athena query comments

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt

Added missing bracket to the property value.

Dpr2 945 fix workgroup property

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/model/Prompt.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ConfiguredApiServiceTest.kt

Wrap date prompts in toDate function while constructing the prompt_ CTE and default the format to `yyyy-mm-dd`.

DPR2-1038 addition of toDate function for date prompts

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiSyncController.kt

Amended swagger documentation regarding the use of filters deriving from prompts in the async API.

Amend swagger documentation

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/MetricsDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/MetricDataResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AbstractProductDefinitionRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SingleMetricProductDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricsDataService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiService.kt
src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTestContainersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/MetricDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/MetricsDataIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricDefinitionServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/MetricsDataServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/SyncDataApiServiceTest.kt
src/test/resources/productDefinitionWithMetrics.json

The following changes create the new metrics data API.

DPR2-1129 added new metrics data API

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ClientDataProductDefinitionsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ProductDefinitionRepositoryAutoConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/AuthenticationHelper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/security/ContextAuthenticationHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/JwtAuthHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/TestAuthenticationHelper.kt

- Added wrapper for security context.
- Improved test coverage.
- Swapped out deprecated token methods.
- Removed unused parameter.

[DPR2-1355] Test coverage for Definitions API authentication

---

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/MetricDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Metric.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/DashboardDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt
src/test/resources/productDefinitionWithMetrics.json

Updated the dashboard definition.

DPR2-1433 updated dashboard definition

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/RedshiftDataApiIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt

New statement status endpoint.

DPR2-1464 status endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RedshiftDataApiRepositoryTest.kt

Fix dashboard execution query issue.

Dpr2 1486 fix dashboard execution query

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/VariantDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/MetaData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Report.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ReportMetadata.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt
src/test/resources/productDefinition.json

Added report metadata hint to support the interactive journey.

Dpr2 1453 report metadata

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/establishmentsAndWings/EstablishmentsToWingsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/estcodesandwings/EstablishmentCodesToWingsCacheService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/estcodesandwings/RefreshCacheSchedulingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/establishmentsAndWings/EstablishmentsToWingsRepositoryTest.kt

Fixed issue with retrieving list of establishments and wings when there is more than one page of results in Athena.
Added some debug logging.

DPR2-1075- Fixed issue with establishments and wings paginated results

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapperTest.kt

Return only the establishment description as the FilterOption display value.

DPR2-1614- Return only the establishment description as the FilterOption display value

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/DataApiAsyncController.kt

Changes include:
- Made the creation of DataApiAsyncController conditional on dpr.lib.aws.sts.enabled being true.
- Removed try/catch blocks of NPE in the Controller.

NO_JIRA conditional DataApiAsyncController

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/FilterType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/GranularityDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/QuickFilterDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/FilterType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Granularity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/QuickFilter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DefinitionMapper.kt

Added defaultGranularity and defaultQuickFilterValue to Fiters

DPR2-1655 Added defaultGranularity and defaultQuickFilterValue to Filters

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/SchemaField.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DefinitionMapper.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionMapperTest.kt

With these changes the dashboard definition response converts dataset parameters to filters.

Dpr2 1749 prompts for dashboards

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/AggregateTypeDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardSectionDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardVisualisationColumnDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardVisualisationColumnsDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardVisualisationDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/DashboardVisualisationTypeDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/UnitTypeDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/ValueVisualisationColumnDefinition.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/AggregateType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Dashboard.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardSection.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardVisualisation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardVisualisationColumn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardVisualisationColumns.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/DashboardVisualisationType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/UnitType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/ValueVisualisationColumn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionMapper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/DashboardDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/integration/ReportDefinitionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionMapperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/DashboardDefinitionServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/ReportDefinitionSummaryMapperTest.kt
src/test/resources/productDefinitionWithMetrics.json

Updated dashboard schema based on FE changes.
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-frontend/pull/339

DPR2-1740 update dashboard definition

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/RepositoryHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/ConfiguredApiRepositoryTest.kt

Fixed issue with more than one multiselect filters in which the same filter value was applied to different columns.

DPR2-1827 fixed issue with multiselect

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt

Changes include fixes around base64 encoding queries and taking into account parameters from multiphase queries when they exist.

Dpr2 1873 multiphase query fixes

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt

Changes to decode the error messages on the API side.
Corresponding changes have been made on the lambda side to encode these.

Dpr2 1873 multiphase queries encode/decode errors

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaApiRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiService.kt

Changes to fix prompts in dashboard multiphase queries.

DPR2-1873 fix prompts issue

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/AthenaAndRedshiftCommonRepository.kt

Added debug logs to log the result query for the async journey

DPR2-1820 Added debug logs to log the result query for the async journey

---

CHANGELOG.md
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/controller/model/Template.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/data/model/Template.kt

Added parent child section template.

Dpr2 1970 added parent child section template

---

src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportinglib/service/AsyncDataApiServiceTest.kt

Added test to verify deduplication of the same prompts in multiphase queries.

DPR2-1915 Added test for deduplicating multiphase prompts

---

CHANGELOG.md

Updated the changelog with the most recent changes made to the Backend library.

DPR2-2007 updated changelog
